### ISSUE TITLE
Sebutkan sumber dan lisensi file-file eksternal

### ISSUE THREAD

**Issue by ceefour** [lskk/assets-game-VidyaNusa#1]
Contoh https://github.com/lskk/assets-game-VidyaNusa/blob/master/garden/1197114378900115008zeimusu_Red_rose.svg.med.png yang diunggah oleh @murtisari 

Sumbernya http://www.clker.com/clipart-14849.html

Semua file yang bukan tim VidyaNusa yang buat sendiri, _wajib_ mencantumkan _sumber_ dan _lisensi_.
Ini agar kita secara legal dapat beroperasi dengan baik secara jangka panjang.

Tidak diperkenankan mengambil materi dari sumber yang tertutup atau tidak berlisensi terbuka.

**Comment by murtisari** [comment]
http://www.clker.com/clipart-13218.html

Saya dapat dari sini Pak.. apa tidak boleh ya Pak jika mengambil dari sini?

**Comment by ceefour** [comment]
@murtisari Harusnya boleh, tapi sebutkan sumber dan lisensinya.

Dimasukkan di sini ya : https://github.com/lskk/assets-game-VidyaNusa/blob/master/SOURCES.md

Saya sudah berikan satu contoh untuk yang red rose tadi, tinggal dilengkapi untuk file-file lain yang eksternal.

**Comment by murtisari** [comment]
sudah ya Pak :D

**Comment by ceefour** [comment]
@murtisari kalo udah, silakan close issue ini ya

**Comment by ceefour** [comment]
@murtisari Ternyata belum selesai...

Maaf tadi saya salah kasih contoh, berikut klarifikasinya:
1. Yang dimaksud **Source** adalah URL sumber gambarnya, misal http://www.clker.com/clipart-14849.html
2. Lisensi belum tentu Public domain, tergantung sumbernya. Kadang sumber mencantumkan Creative Commons Attribution 4.0, atau lisensi lain.
3. Hanya file eksternal saja yang dimasukkan, bukan file buatan kita sendiri.

**Comment by murtisari** [comment]
sudah Pak, cuma untuk mengecek public domain saya kurang tau Pak..

**Comment by ceefour** [comment]
Thanks @murtisari
